version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ".docker/go/Dockerfile"
    container_name: "grpc-bidirectional-app"
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ".:/app"